# Generated by Django 5.0.8 on 2024-10-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='alternate_email',
            new_name='alternative_email',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='alternate_phone_number',
            new_name='alternative_phone_number',
        ),
    ]
