# Generated by Django 5.0.8 on 2024-10-17 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_alternate_email_userinfo_alternative_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingorder',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^0\\d{10}$', 'Mobile number should be 11 digits starting with 0.')]),
        ),
    ]
