# Generated by Django 5.0.8 on 2024-11-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_pendingorder_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedorder',
            name='price',
            field=models.IntegerField(default=23333),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='price',
            field=models.IntegerField(default=324535),
            preserve_default=False,
        ),
    ]
