# Generated by Django 5.0.8 on 2024-11-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_completedorder_price_pendingorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedorder',
            name='address',
            field=models.TextField(default='Head OfficeShop 9, F. Abel Complex, Opp Polaris bank, Abayomi, Iwo Road, Ibadan, Oyo State, Nigeria.BranchShop10, Railway Shopping Complex, Opposite IBEDC, Dugbe, Ibadan, Oyo State, Nigeria.'),
            preserve_default=False,
        ),
    ]
