# Generated by Django 5.2.1 on 2025-06-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_completedorder_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pendingorder',
            options={'ordering': ['-created_at']},
        ),
    ]
