# Generated by Django 5.0.8 on 2024-10-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(default='wejkhdjwe', max_length=100),
            preserve_default=False,
        ),
    ]
