# Generated by Django 5.0.8 on 2024-10-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session_data',
            field=models.TextField(default='eyJjYXJ0Ijp7fSwiYWRkcmVzcyI6e319:1t6DqI:GQmLk8mh7CLeuTd9s9xTbqnP55h5RkcuqkpyzADo5mI'),
            preserve_default=False,
        ),
    ]
