# Generated by Django 5.0.8 on 2024-11-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_session_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='access_code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(max_length=30),
        ),
    ]
