# Generated by Django 5.0.8 on 2024-11-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_forgotpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneverification',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
        migrations.DeleteModel(
            name='PhoneVerification',
        ),
    ]
