# Generated by Django 5.0.8 on 2024-11-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lga',
            name='delivery_data',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lga',
            name='delivery_fee',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
    ]
