# Generated by Django 5.0.8 on 2024-11-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_lga_delivery_data_lga_delivery_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lga',
            old_name='delivery_data',
            new_name='delivery_days',
        ),
    ]
