# Generated by Django 5.0.8 on 2024-11-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_deal_options_deal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='link_to',
            field=models.URLField(max_length=500),
        ),
    ]
